# Generated by Django 3.2 on 2023-04-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=20)),
                ('birth_year', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cats',
            },
        ),
    ]
