# Generated by Django 3.2 on 2023-04-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20230424_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_purebred',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
