# Generated by Django 3.2 on 2023-04-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_cat_is_purebred'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteToyCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.toy')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='toy',
            field=models.ManyToManyField(through='cats.FavouriteToyCat', to='cats.Toy'),
        ),
    ]
