# Generated by Django 3.2 on 2023-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_auto_20230424_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='deleted',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
