# Generated by Django 3.2 on 2023-04-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_cat_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='toy',
            new_name='toys',
        ),
        migrations.AlterField(
            model_name='cat',
            name='is_purebred',
            field=models.BooleanField(default=False),
        ),
    ]
